language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ng-multipage' ]; then cd .. && eval "mv $currentfolder generator-ng-multipage" && cd generator-ng-multipage; fi
